// <auto-generated />
using System;
using BeefCakeData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeefCakeData.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20211020084117_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BeefCakeData.Model.Measurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Bmi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Measurements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bmi = 22.2m,
                            Calories = 3000,
                            Date = new DateTime(2021, 10, 20, 10, 41, 16, 803, DateTimeKind.Local).AddTicks(386),
                            UserId = 1,
                            Weight = 68.5m
                        },
                        new
                        {
                            Id = 2,
                            Bmi = 23.3m,
                            Calories = 3500,
                            Date = new DateTime(2021, 10, 20, 10, 41, 16, 819, DateTimeKind.Local).AddTicks(17),
                            UserId = 2,
                            Weight = 80m
                        },
                        new
                        {
                            Id = 3,
                            Bmi = 22.7m,
                            Calories = 2000,
                            Date = new DateTime(2021, 10, 20, 10, 41, 16, 819, DateTimeKind.Local).AddTicks(89),
                            UserId = 3,
                            Weight = 78m
                        },
                        new
                        {
                            Id = 4,
                            Bmi = 18.6m,
                            Calories = 1900,
                            Date = new DateTime(2021, 10, 20, 10, 41, 16, 819, DateTimeKind.Local).AddTicks(105),
                            UserId = 4,
                            Weight = 54.0m
                        });
                });

            modelBuilder.Entity("BeefCakeData.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1992, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = 1,
                            Height = 175m,
                            Name = "Grzesiek"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1982, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = 1,
                            Height = 185m,
                            Name = "Piotr"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1994, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = 1,
                            Height = 185m,
                            Name = "Łukasz"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1992, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = 0,
                            Height = 170m,
                            Name = "Sylwia"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
